// import { getPages } from "@/sanity/sanity-utils";
import "../globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import NavBar from "./common/NavBar";
import Footer from "./common/Footer";
import Head from "next/head";
import Script from "next/script";
import MoveToTop from "./common/MoveToTop";
import PriventScreenShot from "./common/PriventScreenShot";
import PriventKeyListner from "./common/PriventKeyListner";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const pages = await getPages();
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <section id="Nav">
          <NavBar />
        </section>
        {children}
        <Footer />
        <PriventScreenShot />
        <MoveToTop />
        <PriventKeyListner />
      </body>
    </html>
  );
}
